import {
  __resetCatalogApiCaches,
  fetchEntityDetail,
  fetchHistoryPage,
  fetchIndex,
  fetchLocaleDuplicates,
  fetchManifest,
  setCatalogRouterMode,
} from "./api";

describe("catalog api", function () {
  const originalFetch = global.fetch;

  afterEach(function () {
    global.fetch = originalFetch;
    __resetCatalogApiCaches();
    setCatalogRouterMode("browser");
  });

  it("decodes compact indexes while preserving the public index shape", async function () {
    const fetchMock = jest.fn().mockResolvedValue({
      ok: true,
      json: async () => ({
        set: "root",
        formatVersion: 2,
        counts: { locale: 0, message: 1, attribute: 0, segment: 0, target: 0 },
        dictionaries: { targets: ["web"], locales: ["en"] },
        entities: {
          message: {
            columns: ["key", "targets", "locales"],
            rows: [["welcome", 1, 1]],
          },
        },
      }),
    });
    global.fetch = fetchMock as unknown as typeof fetch;

    await expect(fetchIndex()).resolves.toMatchObject({
      entities: {
        message: [
          {
            key: "welcome",
            targets: ["web"],
            locales: ["en"],
            href: "entities/message/welcome.json",
          },
        ],
      },
    });
  });

  it("loads message details from a block layout and caches the block", async function () {
    const manifest = {
      schemaVersion: "1",
      generatedAt: "2026-01-01T00:00:00.000Z",
      sets: false,
      setKeys: [],
      layout: {
        version: 1,
        mode: "blocks",
        blockSize: 262144,
        vbucketBits: 16,
        blockedTypes: ["message"],
      },
      paths: { projectHistory: "data/project/history/page-1.json" },
      counts: { root: { locale: 0, message: 1, attribute: 0, segment: 0, target: 0 } },
    };
    const detail = { type: "message", key: "welcome", entity: { translations: {} } };
    const fetchMock = jest.fn().mockImplementation(async (url: string) => {
      if (url === "/data/manifest.json") {
        return { ok: true, json: async () => manifest };
      }

      if (url === "/data/root/blocks/message/ranges.json") {
        return {
          ok: true,
          json: async () => ({
            layoutVersion: 1,
            vbucketBits: 16,
            blockSize: 262144,
            blocks: [[0, "block-hash"]],
          }),
        };
      }

      if (url === "/data/root/blocks/message/block-hash.json") {
        return { ok: true, json: async () => ({ welcome: detail }) };
      }

      throw new Error(`Unexpected URL: ${url}`);
    });
    global.fetch = fetchMock as unknown as typeof fetch;

    await fetchManifest();
    await expect(fetchEntityDetail("message", "welcome")).resolves.toEqual(detail);
    await expect(fetchEntityDetail("message", "welcome")).resolves.toEqual(detail);

    expect(fetchMock).toHaveBeenCalledTimes(3);
  });

  it("rejects a Catalog layout newer than the UI understands", async function () {
    const fetchMock = jest.fn().mockResolvedValue({
      ok: true,
      json: async () => ({
        schemaVersion: "1",
        generatedAt: "2026-01-01T00:00:00.000Z",
        sets: false,
        setKeys: [],
        layout: {
          version: 2,
          mode: "blocks",
          blockSize: 262144,
          vbucketBits: 16,
          blockedTypes: [],
        },
        paths: { projectHistory: "data/project/history/page-1.json" },
        counts: {},
      }),
    });
    global.fetch = fetchMock as unknown as typeof fetch;

    await fetchManifest();

    await expect(fetchEntityDetail("message", "welcome")).rejects.toThrow(
      "generated by a newer Messagevisor version",
    );
  });

  it("fetches locale duplicates from the expected root data path", async function () {
    const fetchMock = jest.fn().mockResolvedValue({
      ok: true,
      json: async () => ({
        locale: "en-US",
        summary: { duplicateValues: 0, duplicateMessageKeys: 0 },
        duplicateValues: [],
      }),
    });
    global.fetch = fetchMock as unknown as typeof fetch;

    await fetchLocaleDuplicates("en-US");

    expect(fetchMock).toHaveBeenCalledWith("/data/root/duplicates/locales/en-US.json");
  });

  it("fetches locale duplicates from the expected set data path", async function () {
    const fetchMock = jest.fn().mockResolvedValue({
      ok: true,
      json: async () => ({
        locale: "nl-NL",
        summary: { duplicateValues: 0, duplicateMessageKeys: 0 },
        duplicateValues: [],
      }),
    });
    global.fetch = fetchMock as unknown as typeof fetch;

    await fetchLocaleDuplicates("nl-NL", "staging");

    expect(fetchMock).toHaveBeenCalledWith("/data/sets/staging/duplicates/locales/nl-NL.json");
  });

  it("treats a missing first history page as empty history", async function () {
    const fetchMock = jest.fn().mockResolvedValue({
      ok: false,
      status: 404,
    });
    global.fetch = fetchMock as unknown as typeof fetch;

    await expect(fetchHistoryPage("data/root/history/message/common.welcome", 1)).resolves.toEqual({
      page: 1,
      pageSize: 50,
      totalPages: 1,
      entries: [],
    });
  });

  it("treats a browser-router HTML fallback for first history page as empty history", async function () {
    const fetchMock = jest.fn().mockResolvedValue({
      ok: true,
      headers: new Headers({ "content-type": "text/html" }),
      json: async () => {
        throw new Error("Should not parse HTML as JSON");
      },
    });
    global.fetch = fetchMock as unknown as typeof fetch;

    await expect(fetchHistoryPage("data/root/history/message/common.welcome", 1)).resolves.toEqual({
      page: 1,
      pageSize: 50,
      totalPages: 1,
      entries: [],
    });
  });

  it("keeps later missing history pages as load errors", async function () {
    const fetchMock = jest.fn().mockResolvedValue({
      ok: false,
      status: 404,
    });
    global.fetch = fetchMock as unknown as typeof fetch;

    await expect(fetchHistoryPage("data/root/history/message/common.welcome", 2)).rejects.toThrow(
      "Unable to load",
    );
  });
});
