export interface CLIOptionDefinition {
  type: "array" | "boolean" | "number" | "string";
  alias?: string | string[];
  choices?: readonly string[];
  description?: string;
}

export type CLIOptionDefinitions = Record<string, CLIOptionDefinition>;

const outputOptions: CLIOptionDefinitions = {
  json: { type: "boolean", description: "print structured JSON output" },
  pretty: { type: "boolean", description: "pretty-print JSON output" },
};

const setOption: CLIOptionDefinitions = {
  set: { type: "string", description: "select a project set" },
};

const messageFilters: CLIOptionDefinitions = {
  includeMessages: { type: "array", description: "include matching message keys" },
  excludeMessages: { type: "array", description: "exclude matching message keys" },
};

const definitions: Record<string, CLIOptionDefinitions> = {
  benchmark: {
    ...outputOptions,
    ...setOption,
    locale: { type: "string", description: "locale to evaluate" },
    target: { type: "string", description: "target datafile to evaluate" },
    message: { type: "string", description: "message key to evaluate" },
    rawMessage: { type: "string", description: "raw message to format" },
    values: { type: "string", description: "JSON message values" },
    context: { type: "string", description: "JSON targeting context" },
    n: { type: "number", description: "number of evaluations" },
  },
  build: {
    ...outputOptions,
    ...setOption,
    target: { type: "string", description: "build one target" },
    locale: { type: "string", description: "build one locale" },
    revision: { type: "string", description: "override the generated revision" },
    stateFiles: { type: "boolean", description: "write build state files" },
    showSize: { type: "boolean", description: "show generated datafile sizes" },
  },
  catalog: {
    set: { type: "array", description: "include one or more sets" },
    outDir: { type: "string", description: "Catalog output directory" },
    port: { type: "number", alias: "p" },
    assets: { type: "boolean", description: "copy Catalog UI assets; use --no-assets to skip" },
    noAssets: { type: "boolean", description: "skip copying Catalog UI assets" },
    hashRouter: { type: "boolean", description: "use hash-based browser routes" },
    blockSize: { type: "number", description: "Catalog block size in bytes" },
    prettyOutput: { type: "boolean", description: "pretty-print generated Catalog JSON" },
    withDuplicates: { type: "boolean", description: "generate duplicate reports" },
    withTranslationSearch: { type: "boolean", description: "generate translation search data" },
  },
  config: outputOptions,
  create: {
    ...outputOptions,
    ...setOption,
    keys: { type: "string", description: "newline-separated entity keys" },
    messages: { type: "boolean" },
    locales: { type: "boolean" },
    targets: { type: "boolean" },
    attributes: { type: "boolean" },
    segments: { type: "boolean" },
  },
  diff: {
    ...outputOptions,
    set: { type: "array" },
    from: { type: "string", description: "source Git ref" },
    to: { type: "string", description: "destination Git ref" },
    format: { type: "string", choices: ["terminal", "markdown", "json"] },
    resolved: { type: "boolean", description: "include resolved locale inheritance changes" },
  },
  evaluate: {
    ...outputOptions,
    ...setOption,
    locale: { type: "string", description: "locale to evaluate" },
    target: { type: "string", description: "target datafile to evaluate" },
    message: { type: "string", description: "message key to evaluate" },
    rawMessage: { type: "string", description: "raw message to format" },
    segment: { type: "string", description: "segment key to evaluate" },
    values: { type: "string", description: "JSON message values" },
    context: { type: "string", description: "JSON targeting context" },
  },
  examples: {
    ...outputOptions,
    ...setOption,
    locale: { type: "string", description: "filter by locale" },
    exampleIndex: { type: "number" },
    matrixIndex: { type: "number" },
    descriptionPattern: { type: "string" },
    translationPattern: { type: "string" },
    onlyMessages: { type: "boolean" },
    onlyLocales: { type: "boolean" },
    includeEvaluationInput: { type: "boolean" },
  },
  export: {
    ...messageFilters,
    set: { type: "array" },
    locale: { type: "array" },
    target: { type: "array" },
    output: { type: "string" },
    delimiter: { type: "string" },
    lineEnding: { type: "string", choices: ["lf", "crlf"] },
    bom: { type: "boolean" },
    print: { type: "boolean" },
    force: { type: "boolean" },
    onlyUntranslated: { type: "boolean" },
    onlyDirectlyUntranslated: { type: "boolean" },
    excludeOverrides: { type: "boolean" },
    withoutDescription: { type: "boolean" },
    withoutStatus: { type: "boolean" },
  },
  "find-duplicates": {
    ...outputOptions,
    ...setOption,
    locale: { type: "string", description: "filter by locale" },
  },
  "find-usage": {
    ...outputOptions,
    ...setOption,
    message: { type: "string" },
    segment: { type: "string" },
    attribute: { type: "string" },
    locale: { type: "string" },
    format: { type: "string" },
  },
  "generate-code": {
    ...messageFilters,
    ...setOption,
    target: { type: "string" },
    language: { type: "string", choices: ["typescript"] },
    outDir: { type: "string" },
    react: { type: "boolean" },
  },
  import: {
    set: { type: "array" },
    locale: { type: "array" },
    input: { type: "string" },
    delimiter: { type: "string" },
    bom: { type: "boolean" },
    apply: { type: "boolean" },
    prune: { type: "boolean" },
    createMissing: { type: "boolean" },
    fromJson: { type: "boolean" },
    jsonPath: { type: "string" },
  },
  info: { ...outputOptions, ...setOption },
  init: {
    project: { type: "string" },
    overwrite: { type: "boolean" },
  },
  lint: {
    ...outputOptions,
    ...setOption,
    entityType: {
      type: "string",
      choices: ["project", "locale", "attribute", "segment", "message", "target", "test"],
    },
    keyPattern: { type: "string" },
  },
  list: {
    ...outputOptions,
    ...setOption,
    datafiles: { type: "boolean" },
    messages: { type: "boolean" },
    locales: { type: "boolean" },
    segments: { type: "boolean" },
    attributes: { type: "boolean" },
    targets: { type: "boolean" },
    tests: { type: "boolean" },
    target: { type: "array" },
    locale: { type: "string" },
    keyPattern: { type: "string" },
    description: { type: "string" },
    type: { type: "string" },
    archived: { type: "boolean" },
    deprecated: { type: "boolean" },
    promotable: { type: "boolean" },
    inheritFormatsFrom: { type: "string" },
    inheritTranslationsFrom: { type: "string" },
    withContext: { type: "boolean" },
    withoutContext: { type: "boolean" },
    withFormats: { type: "boolean" },
    withoutFormats: { type: "boolean" },
    withMeta: { type: "boolean" },
    withoutMeta: { type: "boolean" },
    withOverrides: { type: "boolean" },
    withoutOverrides: { type: "boolean" },
    withTests: { type: "boolean" },
    withoutTests: { type: "boolean" },
    applyMatrix: { type: "boolean" },
  },
  promote: {
    ...messageFilters,
    from: { type: "string" },
    to: { type: "string" },
    target: { type: "array" },
    locale: { type: "array" },
    excludeOverrides: { type: "boolean" },
    conflicts: { type: "string", choices: ["source", "destination", "fail"] },
    audit: { type: "string" },
    allowEmpty: { type: "boolean" },
    showUnchanged: { type: "boolean" },
    apply: { type: "boolean" },
  },
  prune: {
    ...messageFilters,
    ...setOption,
    translations: { type: "boolean" },
    formats: { type: "boolean" },
    locale: { type: "array" },
    target: { type: "array" },
    apply: { type: "boolean" },
  },
  test: {
    ...outputOptions,
    ...setOption,
    keyPattern: { type: "string" },
    assertionPattern: { type: "string" },
    onlyFailures: { type: "boolean" },
    showDatafile: { type: "boolean" },
    verbose: { type: "boolean" },
  },
};

export function getBuiltinCLIOptions(command: string): CLIOptionDefinitions {
  return definitions[command.split(" ")[0]] || {};
}
